# Generated by Django 5.1.4 on 2025-01-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("VEGETABLE", "Vegetable"),
                    ("FRUIT", "Fruit"),
                    ("DRY_FRUIT", "Dry Fruit"),
                    ("BREAD", "Bread"),
                    ("MEAT", "Meat"),
                ],
                max_length=10,
            ),
        ),
    ]
