# Generated by Django 5.1.1 on 2025-01-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="rating",
            field=models.IntegerField(
                choices=[
                    (1, "One"),
                    (2, "Two"),
                    (3, "Three"),
                    (4, "Four"),
                    (5, "Five"),
                ],
                default=5,
            ),
        ),
    ]
