# Generated by Django 5.1.1 on 2025-01-22 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_remove_product_id_alter_product_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="producttag",
            name="product",
        ),
    ]
