# Generated by Django 5.1.1 on 2025-01-25 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_coupon"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="is_always_valid",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="valid_from",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="valid_to",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
