# Generated by Django 5.1.1 on 2025-01-27 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_coupon_is_always_valid_alter_coupon_valid_from_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="quantity",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="quantity_type",
            field=models.CharField(
                choices=[
                    ("NOT_SET", "Not Set"),
                    ("KG", "Kg"),
                    ("GRAM", "Gram"),
                    ("LITRE", "Litre"),
                    ("ML", "Ml"),
                    ("DOZEN", "Dozen"),
                    ("BOTTLE", "Bottle"),
                    ("CAN", "Can"),
                ],
                default="NOT_SET",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
