# Generated by Django 5.1.1 on 2025-01-27 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_product_quantity_product_quantity_type_product_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="extra_info",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
