# Generated by Django 5.1.1 on 2025-01-27 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0012_alter_product_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="short_description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
