# Generated by Django 5.1.1 on 2025-01-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0014_productreview"),
    ]

    operations = [
        migrations.AddField(
            model_name="productreview",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
