# Generated by Django 5.1.1 on 2025-02-04 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0015_productreview_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="quantity_type",
            new_name="unit",
        ),
    ]
