# Generated by Django 5.1.1 on 2025-02-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0016_rename_quantity_type_product_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="unit",
            field=models.CharField(
                choices=[
                    ("NOT_SET", "Not Set"),
                    ("Kg", "Kg"),
                    ("g", "Gram"),
                    ("L", "Litre"),
                    ("mL", "Ml"),
                    ("DOZEN", "Dozen"),
                    ("BOTTLE", "Bottle"),
                    ("CAN", "Can"),
                ],
                default="NOT_SET",
                max_length=10,
            ),
        ),
    ]
