# Generated by Django 5.1.1 on 2025-02-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0017_alter_product_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="quantity",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
