# Generated by Django 5.1.1 on 2025-02-14 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0018_alter_product_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="quantity",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
