# Generated by Django 5.1.1 on 2025-05-27 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0019_alter_product_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discounted_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
