# Generated by Django 5.1.4 on 2025-01-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="alternate_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=10,
                null=True,
                unique=True,
                verbose_name="Alternate Number",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="mobile",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=10,
                null=True,
                unique=True,
                verbose_name="Mobile Number",
            ),
        ),
    ]
