# Generated by Django 5.1.1 on 2025-01-22 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_cart_cartitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cart",
            name="profile",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart",
                to="users.profile",
            ),
        ),
    ]
