# Generated by Django 5.1.1 on 2025-01-22 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_cart_ip_address_alter_cart_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="product_discounted_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
