# Generated by Django 5.1.1 on 2025-01-22 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_cartitem_product_discounted_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="product",
        ),
    ]
