# Generated by Django 5.1.1 on 2025-01-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_cartitem_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
