# Generated by Django 5.1.1 on 2025-01-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_cartitem_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="cover_photo",
            field=models.ImageField(
                blank=True,
                default="users/cover_photos/default_cover.jpg",
                null=True,
                upload_to="users/cover_photos",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="users/profile_pictures/default_profile.png",
                null=True,
                upload_to="users/profile_pictures",
            ),
        ),
    ]
