# Generated by Django 5.1.1 on 2025-05-26 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_profile_cover_photo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="mobile",
        ),
    ]
