# Generated by Django 5.1.1 on 2024-09-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactus",
            name="email",
            field=models.EmailField(
                db_index=True, max_length=254, verbose_name="email address"
            ),
        ),
    ]
